<?php

// --------------------------------------------------------------------
// --- Pose CSS v 1.5 [ Fawn ] | file: pose.config.php
// --- http://posecss.com
// --- Copyright (c) 2010-2011 Jesse Weed | Sublantic
// --- Licensed under the Apache 2.0 License.
// --- http://www.apache.org/licenses/LICENSE-2.0
// --------------------------------------------------------------------
// --------------------------------------------------------------------
// --- This file contains all of pose's user editable settings. Please
// --- make sure this file stays in the same directory as pose.php.
// --- Pose will not function right in it cannot find this config file.
// --- The settings are ordered alphabetically by the variable names.
// --- For more information on how to use this file to confire pose,
// --- please visit http://posecss.com/docs/#configuration_options
// --  All file location to be set relative to your pose.php file.
// -------------------------------------------------------------------



// --------------------------------------------------------------------
// --- THESE SETTINGS MUST BE CONFIGURED AFTER INSTALLATION FOR POSE TO
// --- WORK PROPERLY.  
// --------------------------------------------------------------------

	// --- POSE DIRECTORY
	$this->dir='_source'; // --- The directory where pose has been installed (relative to site root)
	
	// --- POSE DOMAIN
	$this->domain='http://dev/posecss.com'; // --- Your websites domain names


// --------------------------------------------------------------------
// --- THESE SETTINGS HAVE BEEN PRECONFIGURED TO WORK WITH MOST SETUPS.
// --- YOU ARE FREE TO MODIFY THEM AS YOU LIKE, BUT YOU DON'T HAVE TO.
// --------------------------------------------------------------------

	// --- VARIABLE OVERRIDE
	$this->allow_get_variables = true; // true to allow $_GET values override variables, false to disable

	// --- BROWSER FILTERING
	$this->browser_filter = true; // true to allow vendor prefix filtering, false to disable
	$this->browser_guess = false; // true to let pose guess the browser instead of passing via $_GET parameter

	// --- CACHE
	$this->cache = false; // true to make css cacheable. false to disable cache
	$this->cache_expires = date('D, d M Y H:i:s', strtotime('+30 days')).' GMT'; // Future expires date for cache
	
	// --- CHARSET
	$this->charset = 'utf-8'; // --- The character encoding you want to use for your css files
	
	// --- COMMENTS
	$this->coment_remove = 'minify'; // true to remove comments from output false to keep
	// "minify" will remove comments only if the css has been minified
	
	// --- CREDIT
	$this->credit = "/* This CSS file was dynamically generated by the Pose CSS Engine ~ posecss.com */ \n\n";

	// --- GLOBAL INCLUDES
	$this->global_include = false; // To include a file in EVERY css file, add the file name here.
	$this->global_include_location = 'top'; // Whether to include the file at the top or bottom of you css files
	
	// --- MINIFY
	$this->minify = false; // true to minify your css, fals eto leave it alone
	
	// --- PLUGINS
	$this->plugins_dir = 'plugins'; // --- The name & location of the plugin directory
	
	// --- SAVE TO FILE
	$this->save = false; // false to display css in brower. true to save to file instead.
	
	$this->save_location = "../styles.css"; //
	
	
// -------------------------------
// --- End of pose.config.php ----
// -------------------------------